kind: PersistentVolume
apiVersion: v1
metadata:
  name: airflow-pv
  labels:
    type: local
    app: airflow
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/k8s/airflow"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: airflow-pvc
  labels:
    app: airflow
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
