apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-deployment
  labels:
    app: airflow
spec:
  replicas: 2
  selector:
    matchLabels:
      app: airflow
  template:
    metadata:
      labels:
        app: airflow
    spec:
      containers:
      - name: airflow
        image: gajuambi/airflow-centos7
        ports:
        - containerPort: 8080
        volumeMounts:
            - name: airflow-persistent-storage
              mountPath: /opt/app-root/src/airflow
      volumes:
      - name: airflow-persistent-storage
        persistentVolumeClaim:
          claimName: airflow-pvc
